<?php

namespace Database\Factories;

use App\Models\User;
use App\Models\Cabang;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\VoucherRequest>
 */
class VoucherRequestFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $user = User::first() ?? User::factory()->create();
        $cabang = Cabang::first() ?? Cabang::factory()->create();

        return [
            'voucher_number' => null, // Will be auto-generated by observer
            'voucher_date' => $this->faker->dateTimeBetween('-1 month', '+1 month'),
            'amount' => $this->faker->randomFloat(2, 100000, 10000000),
            'related_party' => $this->faker->company(),
            'description' => $this->faker->sentence(10),
            'status' => 'draft',
            'created_by' => $user->id,
            'approved_by' => null,
            'approved_at' => null,
            'approval_notes' => null,
            'cabang_id' => $cabang->id,
            'cash_bank_transaction_id' => null,
        ];
    }

    /**
     * Indicate that the voucher is pending approval.
     */
    public function pending(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'pending',
        ]);
    }

    /**
     * Indicate that the voucher is approved.
     */
    public function approved(): static
    {
        $approver = User::first() ?? User::factory()->create();

        return $this->state(fn (array $attributes) => [
            'status' => 'approved',
            'approved_by' => $approver->id,
            'approved_at' => now(),
            'approval_notes' => $this->faker->sentence(),
        ]);
    }

    /**
     * Indicate that the voucher is rejected.
     */
    public function rejected(): static
    {
        $approver = User::first() ?? User::factory()->create();

        return $this->state(fn (array $attributes) => [
            'status' => 'rejected',
            'approved_by' => $approver->id,
            'approved_at' => now(),
            'approval_notes' => $this->faker->sentence(),
        ]);
    }

    /**
     * Indicate that the voucher is cancelled.
     */
    public function cancelled(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'cancelled',
        ]);
    }

    /**
     * Indicate that the voucher has a cabang.
     */
    public function withCabang(): static
    {
        $cabang = Cabang::first() ?? Cabang::factory()->create();

        return $this->state(fn (array $attributes) => [
            'cabang_id' => $cabang->id,
        ]);
    }
}
