<?php

use App\Filament\Resources\OrderRequestResource;

test('large order request editor is limited to edit operations with at least 25 items', function () {
    expect(OrderRequestResource::usesLargeOrderRequestItemEditor(array_fill(0, 24, []), 'edit'))->toBeFalse()
        ->and(OrderRequestResource::usesLargeOrderRequestItemEditor(array_fill(0, 25, []), 'edit'))->toBeTrue()
        ->and(OrderRequestResource::usesLargeOrderRequestItemEditor(array_fill(0, 120, []), 'create'))->toBeFalse();
});

test('large order request navigator keeps server pagination and single editor controls', function () {
    $projectRoot = dirname(__DIR__, 2);
    $resource = file_get_contents($projectRoot . '/app/Filament/Resources/OrderRequestResource.php');
    $editPage = file_get_contents($projectRoot . '/app/Filament/Resources/OrderRequestResource/Pages/EditOrderRequest.php');
    $navigator = file_get_contents($projectRoot . '/resources/views/filament/forms/order-request-item-navigator.blade.php');
    $relationManager = file_get_contents($projectRoot . '/app/Filament/Resources/OrderRequestResource/RelationManagers/OrderRequestItemsRelationManager.php');

    expect($resource)->toContain("->slice(\$offset, \$pageSize)")
        ->and($resource)->toContain("'class' => 'dt-or-large-repeater'")
        ->and($resource)->toContain("view('filament.forms.order-request-item-navigator'")
        ->and($resource)->toContain("Hidden::make('_order_request_item_search')")
        ->and($resource)->toContain("Hidden::make('_order_request_item_supplier_filter')")
        ->and($resource)->toContain("Hidden::make('_order_request_item_cabang_filter')")
        ->and($resource)->toContain("Hidden::make('_order_request_item_tax_filter')")
        ->and($resource)->toContain("Hidden::make('_order_request_item_page_size')")
        ->and($resource)->not->toContain("TextInput::make('_order_request_item_search')")
        ->and($resource)->not->toContain("Select::make('_order_request_item_supplier_filter')")
        ->and($navigator)->toContain('.dt-or-large-repeater .fi-fo-repeater-item{display:none!important}')
        ->and($navigator)->not->toContain('.dt-or-large-editor-active{display:block!important}')
        ->and($navigator)->toContain('data-dt-or-filterbar')
        ->and($navigator)->toContain('wire:key="dt-or-navigator-')
        ->and($navigator)->toContain('dt-item-toolbar-left')
        ->and($navigator)->toContain('data-dt-or-filter-toggle')
        ->and($navigator)->toContain('dt-item-filter-badge')
        ->and($navigator)->toContain('data-dt-or-bulk-actions')
        ->and($navigator)->toContain('data-dt-or-collapse-all')
        ->and($navigator)->toContain('dt-item-filter-drawer')
        ->and($navigator)->toContain('data-dt-or-search')
        ->and($navigator)->toContain('data-dt-or-supplier-filter')
        ->and($navigator)->toContain('data-dt-or-cabang-filter')
        ->and($navigator)->toContain('data-dt-or-tax-filter')
        ->and($navigator)->toContain('data-dt-or-page-size')
        ->and($navigator)->toContain('data-dt-or-clear-search')
        ->and($navigator)->toContain('data-dt-or-clear-all')
        ->and($navigator)->toContain('isLoading: false')
        ->and($navigator)->toContain('isAddingItem: false')
        ->and($navigator)->toContain('recentlyAddedKey:')
        ->and($navigator)->toContain('recentlyAddedMessage:')
        ->and($navigator)->toContain('showAddFeedback(key)')
        ->and($navigator)->toContain('clearAddFeedback()')
        ->and($navigator)->toContain('data-dt-add-feedback')
        ->and($navigator)->toContain('Item baru ditambahkan di baris paling atas')
        ->and($navigator)->toContain('Item baru ditampilkan di halaman pertama')
        ->and($navigator)->not->toContain('Item baru ditambahkan dan dibuka di halaman terakhir')
        ->and($navigator)->not->toContain('Halaman terakhir dibuka untuk item baru')
        ->and($navigator)->toContain('data-dt-view-added-item')
        ->and($navigator)->toContain('dt-item-new-row-highlight')
        ->and($navigator)->toContain('Item baru dibuka')
        ->and($navigator)->toContain('expandedKey:')
        ->and($navigator)->toContain('toggleDetail(key)')
        ->and($navigator)->toContain('scrollEditorIntoView(key')
        ->and($navigator)->not->toContain('moveEditorToMount')
        ->and($navigator)->not->toContain('returnEditorToDock')
        ->and($navigator)->not->toContain('bridgeMountedEditorEvents')
        ->and($navigator)->not->toContain('modelBindingFor(element)')
        ->and($navigator)->not->toContain('const commit = this.$wire.set(model, value)')
        ->and($navigator)->not->toContain('data-dt-or-editor-mount')
        ->and($navigator)->not->toContain('dt-item-editor-mount')
        ->and($navigator)->not->toContain('appendChild')
        ->and($navigator)->toContain('collapseAll()')
        ->and($navigator)->toContain('loadingMessage:')
        ->and($navigator)->toContain('async runNavigatorRequest(message, callback)')
        ->and($navigator)->toContain('try {')
        ->and($navigator)->toContain('finally {')
        ->and($navigator)->toContain('data-dt-or-loading-status')
        ->and($navigator)->toContain('data-dt-or-loading-overlay')
        ->and($navigator)->toContain('aria-live="polite"')
        ->and($navigator)->toContain('x-bind:aria-busy=')
        ->and($navigator)->toContain("x-on:input=\"startLoading('Mencari item…')\"")
        ->and($navigator)->toContain('x-on:input.debounce.500ms="updateSearch()"')
        ->and($navigator)->toContain('x-on:keydown.enter.prevent.stop="void 0"')
        ->and($navigator)->toContain("setNavigatorState('_order_request_item_search'")
        ->and($navigator)->toContain("setNavigatorState('_order_request_item_supplier_filter'")
        ->and($navigator)->toContain("setNavigatorState('_order_request_item_cabang_filter'")
        ->and($navigator)->toContain("setNavigatorState('_order_request_item_tax_filter'")
        ->and($navigator)->toContain("setNavigatorState('_order_request_item_page_size'")
        ->and(substr_count($navigator, '$event.target.value'))->toBeGreaterThan(4)
        ->and($navigator)->toContain("'Menerapkan filter…'")
        ->and($navigator)->toContain("'Memuat halaman…'")
        ->and($navigator)->toContain("'Menghapus filter…'")
        ->and($navigator)->toContain("'Menghapus item…'")
        ->and($navigator)->toContain("'Menambahkan item…'")
        ->and($editPage)->toContain('public function addInlineOrderRequestItem(): string')
        ->and($navigator)->toContain('const newKey = await this.$wire.addInlineOrderRequestItem()')
        ->and($navigator)->toContain('this.showAddFeedback(newKey)')
        ->and($navigator)->not->toContain('addButton.click()')
        ->and($navigator)->not->toContain('window.__dtOrAwaitNewItem')
        ->and($navigator)->toContain('x-bind:disabled="isLoading || isAddingItem"')
        ->and($navigator)->toContain("this.\$wire.set('data.' + field, value === '' ? null : value, false)")
        ->and($navigator)->toContain("this.\$wire.set('data._order_request_item_page', 1, false)")
        ->and($navigator)->toContain('return this.$wire.$commit()')
        ->and($navigator)->toContain('setNavigatorPage(page)')
        ->and($navigator)->toContain("runNavigatorRequest('Memuat halaman…', () => setNavigatorPage(")
        ->and(substr_count($navigator, 'type="submit"'))->toBe(0)
        ->and($navigator)->toContain('dt-item-action-col')
        ->and($navigator)->toContain('dt-item-row-actions')
        ->and($navigator)->toContain('data-dt-delete-item')
        ->and($navigator)->toContain('removeInlineItem(@js($row')
        ->and($navigator)->toContain('dt-item-delete-text')
        ->and($navigator)->toContain('position:sticky;right:0')
        ->and($navigator)->toContain('colspan="11"')
        ->and($navigator)->toContain('dt-item-detail-row')
        ->and($navigator)->toContain('dt-item-detail-card')
        ->and($navigator)->toContain('Editor item #')
        ->and($navigator)->toContain('data-dt-inline-editor')
        ->and($navigator)->toContain('data-dt-inline-product')
        ->and($navigator)->toContain('data-dt-inline-supplier')
        ->and($navigator)->toContain('data-dt-inline-cabang')
        ->and($navigator)->toContain('dt-item-inline-select')
        ->and($navigator)->toContain('appearance:none')
        ->and($navigator)->toContain('background-repeat:no-repeat')
        ->and($navigator)->toContain('text-overflow:ellipsis')
        ->and($navigator)->toContain('data-dt-inline-quantity')
        ->and($navigator)->toContain('data-dt-inline-unit-price')
        ->and($navigator)->toContain('data-dt-inline-discount')
        ->and($navigator)->toContain('data-dt-inline-tax-type')
        ->and($navigator)->toContain('data-dt-inline-subtotal')
        ->and($navigator)->toContain('updateInlineItem(@js($row')
        ->and($navigator)->toContain('Cabang:')
        ->and($navigator)->toContain('Available stock:')
        ->and($navigator)->toContain('Total Items:')
        ->and($navigator)->toContain('Total Subtotal (IDR)')
        ->and($navigator)->toContain('$pageNumbers as $pageNumber')
        ->and($navigator)->toContain('dt-item-more')
        ->and($navigator)->not->toContain('dt-item-grid')
        ->and($navigator)->not->toContain('dt-item-metric')
        ->and($navigator)->toContain('.fi-fo-field-wrp:has(.dt-or-large-repeater){height:0!important')
        ->and($navigator)->toContain('.dt-or-large-repeater{height:0!important')
        ->and($navigator)->not->toContain('data-dt-or-close-editor')
        ->and($navigator)->toContain('data-dt-or-add-navigator')
        ->and($navigator)->toContain('[aria-invalid=true]')
        ->and($editPage)->toContain('public function removeInlineOrderRequestItem(string $itemKey): bool')
        ->and($editPage)->toContain("count(\$items) <= 1")
        ->and($editPage)->toContain('inlineOrderRequestItemIsLocked')
        ->and($editPage)->toContain('Item sudah dipakai pada proses pembelian.')
        ->and($editPage)->toContain('PurchaseOrderItem::withoutGlobalScopes()')
        ->and($editPage)->toContain("\$this->data['orderRequestItem'] = \$items")
        ->and($resource)->toContain("'activeFilterCount' => \$activeFilterCount")
        ->and($resource)->toContain("'pageNumbers' => \$pageNumbers")
        ->and($resource)->toContain("'available_stock'")
        ->and($navigator)->toContain('x-bind:disabled="isLoading || isAddingItem"')
        ->and($relationManager)->toContain('canViewForRecord')
        ->and($relationManager)->toContain('EditOrderRequest::class')
        ->and($relationManager)->toContain('return false;')
        ->and($navigator)->not->toContain('<script');
});
